version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql8
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: triple

  redis:
    image: redis:7
    container_name: redis7
    ports:
      - "6379:6379"
    restart: unless-stopped
    command:
      - --requirepass root
